#index:
#    path: /
#    controller: App\Controller\DefaultController::index
#index:
  #  path: /testt
   # controller: App\Controller\TestController::index


upload_pdf:
    path: '/upload-pdf'
    controller: 'App\Controller\YourController::uploadPdf'

